### ISSUE TITLE
make load_nso_or_so_signups more resilient against different column layouts

### ISSUE THREAD

**Issue by erevrav** [dhmay/sdb-officialator#1]
officialator works on games sheets, but not the layout used for scrims. Pointing at a scrim sheet fails with 
`KeyError: "['Time', 'Who'] not in index"`

here's the two layouts of row 2 in each sheet.
games (e.g., "12.18 GAMES!" and "11.13 GAMES!")
`Day	Time	Time	Mins	Scrim Structure	What	Who	Count	Count`

scrims (e.g., "12.11 Scrims")
`Day	Report Time	Scrim Time	Mins	Scrim Structure	What	Count	Count`

if required, headref & I could change the layout we use, but I'd prefer to not perturb that part of the system. :) 

yes, that means there's not a reliable "Who" column for scrims, so probably add a Scrim Time column in the output file, so there's disambiguation.

**Comment by dhmay** [comment]
Fixed. Sort of. The code now works for "12.18 Scrims" but still fails on "11.6 Scrimmages". I don't want to try to handle every possible format... I'm assuming future scrims are more likely to look like 12.18 than 11.6.
